import type { Figure, FigureCategory } from "@/lib/figures-types";

type Row = [string, string, string, string, string, string];

const g = (category: FigureCategory, rows: Row[]): Figure[] =>
  rows.map(([id, name, era, role, bio, voiceHint]) => ({
    id,
    name,
    era,
    role,
    bio,
    category,
    voiceHint,
  }));

export const EXTRA_FIGURES: Figure[] = [
  ...g("uzbek", [
    ["shohruh-mirzo", "Shohruh Mirzo", "1377–1447", "Temuriy hukmdor", "Temurning o‘g‘li, Hirotni ilm markaziga aylantirgan.", "vazmin, ma’rifatparvar"],
    ["gavharshod", "Gavharshod Begim", "1378–1457", "Malika, homiy", "Hirotdagi mashhur madrasa va masjid bunyodkori.", "viqorli, saxovatli"],
    ["ali-qushchi", "Ali Qushchi", "1403–1474", "Astronom, matematik", "Ulug‘bek shogirdi, «Zij» ni yakunlagan.", "aniq, hisobli"],
    ["qozizoda-rumiy", "Qozizoda Rumiy", "1364–1436", "Matematik", "Ulug‘bek ustozi, Samarqand ilm maktabi rahnamosi.", "ustozona, sabrli"],
    ["jamshid-koshiy", "G‘iyosiddin Jamshid Koshiy", "1380–1429", "Matematik", "π sonini 16 xonagacha hisoblagan.", "hisobga berilgan, hayajonli"],
    ["ahmad-fargoniy", "Ahmad al-Farg‘oniy", "798–861", "Astronom", "Nil o‘lchagichi ixtirochisi, «Al-Fusul» muallifi.", "sinchkov, osoyishta"],
    ["abbos-javhariy", "Abbos al-Javhariy", "800–860", "Astronom", "Bag‘dod «Bayt ul-hikma» olimi.", "izlanuvchan"],
    ["marvaziy", "Habash al-Marvaziy", "770–870", "Astronom", "Trigonometrik jadvallar tuzuvchi.", "puxta, tinch"],
    ["ibn-sino-shogird", "Abu Ubayd Juzjoniy", "980–1070", "Tabib, kotib", "Ibn Sinoning shogirdi va hayotnomachisi.", "sodiq, batafsil"],
    ["az-zamaxshariy", "Mahmud az-Zamaxshariy", "1075–1144", "Tilshunos, mufassir", "«Al-Kashshof» muallifi, Xorazm allomasi.", "nozik, mantiqli"],
    ["burhoniddin-marginoniy", "Burhoniddin Marg‘inoniy", "1123–1197", "Faqih", "«Hidoya» asari muallifi.", "adolatli, qat’iy"],
    ["najmiddin-kubro", "Najmiddin Kubro", "1145–1221", "So‘fiy", "Kubroviya tariqati asoschisi.", "ma’naviy, jasur"],
    ["bahouddin-naqshband", "Bahouddin Naqshband", "1318–1389", "So‘fiy", "«Dil ba yoru dast ba kor» shiori sohibi.", "kamtar, hikmatli"],
    ["xoja-ahror", "Xoja Ahror Valiy", "1404–1490", "So‘fiy, davlat arbobi", "Naqshbandiya yetakchisi, sulhparvar.", "vazmin, ta’sirchan"],
    ["so-fi-olloyor", "So‘fi Olloyor", "1644–1721", "Shoir, ilohiyotchi", "«Sabot ul-ojizin» muallifi.", "nasihatgo‘y"],
    ["mashrab", "Boborahim Mashrab", "1640–1711", "Shoir, darvesh", "Isyonkor so‘fiy shoir.", "erkin, olovli"],
    ["ogahiy", "Muhammad Rizo Ogahiy", "1809–1874", "Shoir, tarixchi", "Xorazm tarixnavisi va tarjimon.", "adabiy, sinchkov"],
    ["munis", "Shermuhammad Munis", "1778–1829", "Shoir, tarixchi", "«Firdavs ul-iqbol» muallifi.", "she’riy"],
    ["nodira", "Nodirabegim", "1792–1842", "Shoira, malika", "Qo‘qon adabiy muhiti homiysi.", "nafis, mag‘rur"],
    ["uvaysiy", "Jahon Otin Uvaysiy", "1781–1845", "Shoira", "Ayollar ta’limi tarafdori shoira.", "hissiyotli, dono"],
    ["zebuniso", "Zebuniso Begim", "1638–1702", "Shoira", "Boburiylar sulolasidan shoira.", "nozik, sirli"],
    ["muqimiy", "Muhammad Aminxo‘ja Muqimiy", "1850–1903", "Shoir", "Satirik she’riyat ustasi.", "hazil, kinoyali"],
    ["furqat", "Zokirjon Furqat", "1859–1909", "Shoir, ma’rifatparvar", "Yangilik va ilm targ‘ibotchisi.", "ilg‘or, ochiq"],
    ["behbudiy", "Mahmudxo‘ja Behbudiy", "1875–1919", "Jadid, dramaturg", "«Padarkush» muallifi.", "ma’rifatparvar, jasur"],
    ["fitrat", "Abdurauf Fitrat", "1886–1938", "Olim, yozuvchi", "Jadidchilik mafkurachisi.", "keskin, tahliliy"],
    ["cho-lpon", "Abdulhamid Cho‘lpon", "1897–1938", "Shoir, yozuvchi", "«Kecha va kunduz» muallifi.", "lirik, hurriyatparvar"],
    ["qodiriy", "Abdulla Qodiriy", "1894–1938", "Yozuvchi", "«O‘tkan kunlar» — birinchi o‘zbek romani.", "hikoyanavis, samimiy"],
    ["avloniy", "Abdulla Avloniy", "1878–1934", "Pedagog, shoir", "«Turkiy guliston yoxud axloq» muallifi.", "murabbiy"],
    ["hamza", "Hamza Hakimzoda Niyoziy", "1889–1929", "Shoir, dramaturg", "Yangi teatr asoschilaridan.", "kurashchan"],
    ["oybek", "Oybek", "1905–1968", "Yozuvchi", "«Navoiy» romani muallifi.", "epik, chuqur"],
    ["g-ulom", "G‘afur G‘ulom", "1903–1966", "Shoir, adib", "«Shum bola» muallifi.", "hazilkash, iliq"],
    ["oydin-hojiyeva", "Oydin Hojiyeva", "1942–2015", "Shoira", "Zamonaviy o‘zbek lirikasi vakili.", "mayin"],
    ["zulfiya", "Zulfiya", "1915–1996", "Shoira", "Milliy she’riyat malikasi.", "hazin, nafis"],
    ["erkin-vohidov", "Erkin Vohidov", "1936–2016", "Shoir", "«Ruhlar isyoni» muallifi.", "jarangdor"],
    ["abdulla-oripov", "Abdulla Oripov", "1941–2016", "Shoir", "O‘zbekiston madhiyasi matni muallifi.", "vatanparvar"],
    ["said-ahmad", "Said Ahmad", "1920–2007", "Yozuvchi", "«Kelinlar qo‘zg‘oloni» muallifi.", "kulgili, xalqona"],
    ["odil-yoqubov", "Odil Yoqubov", "1926–2009", "Yozuvchi", "«Ulug‘bek xazinasi» muallifi.", "tarixiy, jiddiy"],
    ["pirimqul-qodirov", "Pirimqul Qodirov", "1928–2010", "Yozuvchi", "«Yulduzli tunlar» muallifi.", "romantik, tarixiy"],
    ["tohir-malik", "Tohir Malik", "1946–2019", "Yozuvchi", "«Shaytanat» muallifi.", "keskin, tarbiyaviy"],
    ["yusuf-xos-hojib", "Yusuf Xos Hojib", "1017–1077", "Shoir, mutafakkir", "«Qutadg‘u bilig» muallifi.", "hikmatli, saroyona"],
    ["ahmad-yugnakiy", "Ahmad Yugnakiy", "XII asr", "Shoir", "«Hibat ul-haqoyiq» muallifi.", "nasihatgo‘y"],
    ["rabg-uziy", "Nosiruddin Rabg‘uziy", "XIII–XIV asr", "Adib", "«Qisasi Rabg‘uziy» muallifi.", "hikoyachi"],
    ["sakkokiy", "Sakkokiy", "XIV–XV asr", "Shoir", "Temuriylar davri qasidanavisi.", "tantanavor"],
    ["lutfiy", "Lutfiy", "1366–1465", "Shoir", "Navoiy ustozlaridan biri.", "nafis, oshiqona"],
    ["husayn-boyqaro", "Husayn Boyqaro", "1438–1506", "Hukmdor, shoir", "Hirot uyg‘onish davri homiysi.", "shoirona, saxiy"],
    ["kamoliddin-behzod", "Kamoliddin Behzod", "1455–1535", "Musavvir", "Sharq miniatyurasi sultoni.", "sinchkov, nafis"],
    ["mahmud-torobiy", "Mahmud Torobiy", "?–1238", "Qo‘zg‘olon rahbari", "Buxorodagi mo‘g‘ullarga qarshi qo‘zg‘olon boshlig‘i.", "jasur, xalqchil"],
    ["jaloliddin-manguberdi", "Jaloliddin Manguberdi", "1198–1231", "Sarkarda", "Mo‘g‘ullarga qarshi kurash timsoli.", "botir, shiddatli"],
    ["temur-malik", "Temur Malik", "XIII asr", "Sarkarda", "Xo‘jand mudofaasi qahramoni.", "mard, qat’iy"],
    ["ismoil-somoniy", "Ismoil Somoniy", "849–907", "Amir", "Somoniylar davlati asoschisi.", "adolatli, tadbirkor"],
    ["mahmud-gaznaviy", "Mahmud G‘aznaviy", "971–1030", "Sulton", "G‘azna imperiyasi hukmdori.", "shijoatli, homiy"],
    ["alp-tegin", "Alptegin", "?–963", "Sarkarda", "G‘aznaviylar asoschisi.", "harbiy, qat’iy"],
    ["tug-rul-bek", "Tug‘rulbek", "990–1063", "Saljuqiy sulton", "Saljuqiylar davlatiga asos solgan.", "shijoatli"],
    ["shayboniyxon", "Muhammad Shayboniyxon", "1451–1510", "Xon", "Shayboniylar sulolasi asoschisi.", "qat’iy, jangovar"],
    ["abdullaxon-ii", "Abdullaxon II", "1534–1598", "Buxoro xoni", "Bunyodkor hukmdor.", "tadbirkor"],
    ["olloqulixon", "Olloqulixon", "1794–1842", "Xiva xoni", "Tosh-hovli saroyi bunyodkori.", "shohona"],
    ["muhammad-rahimxon", "Muhammad Rahimxon II", "1845–1910", "Xiva xoni, shoir", "Feruz taxallusi bilan she’r yozgan.", "nafis, homiy"],
    ["amir-olimxon", "Amir Olimxon", "1880–1944", "Buxoro amiri", "So‘nggi Buxoro amiri.", "og‘ir, ehtiyotkor"],
    ["madalixon", "Muhammad Alixon", "1808–1842", "Qo‘qon xoni", "Qo‘qon xonligining kuchli davri hukmdori.", "yosh, shijoatli"],
    ["dukchi-eshon", "Dukchi Eshon", "1856–1898", "Qo‘zg‘olon rahbari", "Andijon qo‘zg‘oloni boshlig‘i.", "e’tiqodli"],
    ["nazira-nosirova", "Nazira Nosirova", "XX asr", "Aktrisa", "O‘zbek teatri primadonnasi.", "hissiyotli"],
    ["tamaraxonim", "Tamaraxonim", "1906–1991", "Raqqosa", "Milliy raqs maktabi asoschisi.", "jozibali"],
    ["batir-zakirov", "Botir Zokirov", "1936–1985", "Xonanda", "O‘zbek estradasi asoschisi.", "romantik"],
    ["yunus-rajabiy", "Yunus Rajabiy", "1897–1976", "Bastakor", "Shashmaqomni yozib qoldirgan.", "vazmin, ustoz"],
    ["muxtor-ashrafiy", "Muxtor Ashrafiy", "1912–1975", "Kompozitor", "Birinchi o‘zbek operalari muallifi.", "ijodkor"],
    ["sobir-rahimov", "Sobir Rahimov", "1902–1945", "General", "Ikkinchi jahon urushi qahramoni.", "harbiy, qat’iy"],
    ["zulfiya-izzatova", "Zulfiyaxonim Izzatova", "XX asr", "Pedagog", "Ta’lim islohotlari targ‘ibotchisi.", "murabbiy"],
    ["shukur-burhonov", "Shukur Burhonov", "1910–1987", "Aktyor", "Sahna va kino ustasi.", "salobatli"],
    ["obid-sodiqov", "Obid Sodiqov", "1913–1987", "Kimyogar akademik", "O‘zbek kimyo maktabi asoschisi.", "ilmiy"],
    ["habib-abdullayev", "Habib Abdullayev", "1912–1962", "Geolog akademik", "Fanlar akademiyasi prezidenti.", "tadqiqotchi"],
    ["ibrohim-mo-minov", "Ibrohim Mo‘minov", "1908–1974", "Faylasuf", "Temur merosini qayta baholagan.", "jasur, ilmiy"],
    ["voxid-zohidov", "Vohid Zohidov", "1914–1983", "Adabiyotshunos", "Navoiyshunoslik rivojiga hissa.", "tahliliy"],
  ]),
  ...g("science", [
    ["archimedes", "Arximed", "e.a. 287–212", "Matematik, muhandis", "Suzish qonuni va richag nazariyasi.", "hayajonli, kashfiyotchi"],
    ["euclid", "Yevklid", "e.a. 300", "Matematik", "«Negizlar» — geometriya asosi.", "tartibli, mantiqiy"],
    ["pythagoras", "Pifagor", "e.a. 570–495", "Matematik", "Sonlar uyg‘unligi ta’limoti.", "sirli, tartibli"],
    ["hipparchus", "Gipparx", "e.a. 190–120", "Astronom", "Yulduzlar katalogini tuzgan.", "aniq"],
    ["ptolemy", "Ptolemey", "100–170", "Astronom", "«Almagest» muallifi.", "tizimli"],
    ["galen", "Galen", "129–216", "Tabib", "Antik tibbiyot ustuni.", "ishonchli, batafsil"],
    ["hypatia", "Gipatiya", "360–415", "Matematik, faylasuf", "Iskandariya olimasi.", "dono, jasur"],
    ["copernicus", "Nikolay Kopernik", "1473–1543", "Astronom", "Geliotsentrik nazariya.", "ehtiyotkor, inqilobiy"],
    ["tycho", "Tixo Brage", "1546–1601", "Astronom", "Aniq osmon kuzatuvlari.", "mag‘rur, sinchkov"],
    ["kepler", "Iogann Kepler", "1571–1630", "Astronom", "Sayyoralar harakati qonunlari.", "ilhomli, matematik"],
    ["boyle", "Robert Boyl", "1627–1691", "Kimyogar", "Zamonaviy kimyo asoschisi.", "tajribakor"],
    ["huygens", "Xristian Gyuygens", "1629–1695", "Fizik", "Yorug‘likning to‘lqin nazariyasi.", "nozik, aniq"],
    ["leibniz", "Gotfrid Leybnits", "1646–1716", "Matematik, faylasuf", "Differensial hisob asoschisi.", "keng qamrovli"],
    ["euler", "Leonard Eyler", "1707–1783", "Matematik", "Tarixdagi eng sermahsul matematik.", "tinimsiz, aniq"],
    ["lavoisier", "Antuan Lavuazye", "1743–1794", "Kimyogar", "Modda saqlanish qonuni.", "tartibli"],
    ["gauss", "Karl Gauss", "1777–1855", "Matematik", "«Matematiklar shohi».", "mukammallikka intiluvchi"],
    ["faraday", "Maykl Faradey", "1791–1867", "Fizik", "Elektromagnit induksiya.", "sodda, ishtiyoqli"],
    ["maxwell", "Jeyms Maksvell", "1831–1879", "Fizik", "Elektromagnetizm tenglamalari.", "nazariy, nafis"],
    ["mendeleev", "Dmitriy Mendeleyev", "1834–1907", "Kimyogar", "Davriy jadval muallifi.", "ishonchli, tartibli"],
    ["pasteur", "Lui Paster", "1822–1895", "Mikrobiolog", "Vaksina va pasterizatsiya.", "qat’iy, insonparvar"],
    ["koch", "Robert Kox", "1843–1910", "Bakteriolog", "Sil tayoqchasini kashf etgan.", "sinchkov"],
    ["darwin", "Charlz Darvin", "1809–1882", "Tabiatshunos", "Evolyutsiya nazariyasi.", "kuzatuvchan, kamtar"],
    ["mendel", "Gregor Mendel", "1822–1884", "Genetik", "Irsiyat qonunlari.", "sabrli, bog‘bon"],
    ["curie", "Mariya Kyuri", "1867–1934", "Fizik, kimyogar", "Radioaktivlik tadqiqotchisi.", "matonatli, sokin"],
    ["rutherford", "Ernest Rezerford", "1871–1937", "Fizik", "Atom yadrosini kashf etgan.", "hazilkash, aniq"],
    ["planck", "Maks Plank", "1858–1947", "Fizik", "Kvant nazariyasi asoschisi.", "vazmin"],
    ["bohr", "Nils Bor", "1885–1962", "Fizik", "Atom modeli muallifi.", "falsafiy"],
    ["heisenberg", "Verner Geyzenberg", "1901–1976", "Fizik", "Noaniqlik prinsipi.", "chuqur"],
    ["schrodinger", "Ervin Shryodinger", "1887–1961", "Fizik", "To‘lqin tenglamasi.", "tafakkurli"],
    ["dirac", "Pol Dirak", "1902–1984", "Fizik", "Antimateriya bashoratchisi.", "kamgap, aniq"],
    ["feynman", "Richard Feynman", "1918–1988", "Fizik", "Kvant elektrodinamikasi.", "quvnoq, sodda"],
    ["hawking", "Stiven Xoking", "1942–2018", "Kosmolog", "Qora tuynuklar nazariyotchisi.", "hazil, teran"],
    ["turing", "Alan Tyuring", "1912–1954", "Matematik", "Kompyuter fanlari otasi.", "o‘tkir, uyatchan"],
    ["von-neumann", "Yanosh fon Neyman", "1903–1957", "Matematik", "Kompyuter arxitekturasi.", "tez, keskin"],
    ["shannon", "Klod Shennon", "1916–2001", "Muhandis", "Axborot nazariyasi asoschisi.", "o‘ynoqi, aniq"],
    ["lovelace", "Ada Lavleys", "1815–1852", "Matematik", "Birinchi dasturchi.", "orzumand, aniq"],
    ["noether", "Emmi Noter", "1882–1935", "Matematik", "Noter teoremasi muallifi.", "kamtar, teran"],
    ["fibonacci", "Leonardo Fibonachchi", "1170–1250", "Matematik", "Arab raqamlarini Yevropaga olib kirgan.", "amaliy"],
    ["ibn-haysam", "Ibn al-Haysam", "965–1040", "Optika olimi", "Zamonaviy optika asoschisi.", "sinchkov, tajribakor"],
    ["ar-roziy", "Abu Bakr ar-Roziy", "854–925", "Tabib, kimyogar", "Klinik tibbiyot kashshofi.", "shubhachi, aniq"],
    ["ibn-nafis", "Ibn an-Nafis", "1213–1288", "Tabib", "Kichik qon aylanishini kashf etgan.", "tadqiqotchi"],
    ["az-zahroviy", "Abulqosim az-Zahroviy", "936–1013", "Jarroh", "Jarrohlik asboblari ixtirochisi.", "amaliy"],
    ["jobir-ibn-hayyon", "Jobir ibn Hayyon", "721–815", "Kimyogar", "Alkimyo otasi.", "sirli, izlanuvchan"],
    ["al-kindiy", "Al-Kindiy", "801–873", "Faylasuf, olim", "Arab falsafasi otasi.", "keng bilimli"],
    ["at-tusiy", "Nasiriddin at-Tusiy", "1201–1274", "Astronom", "Marog‘a rasadxonasi asoschisi.", "tizimli"],
    ["umar-xayyom", "Umar Xayyom", "1048–1131", "Matematik, shoir", "Taqvim islohotchisi va ruboiynavis.", "falsafiy, nozik"],
    ["semmelweis", "Ignats Zemmelveys", "1818–1865", "Tabib", "Qo‘l gigienasi kashshofi.", "jasur, tashvishli"],
    ["fleming", "Aleksandr Fleming", "1881–1955", "Bakteriolog", "Penitsillin kashfiyotchisi.", "kamtar"],
    ["salk", "Jonas Salk", "1914–1995", "Virusolog", "Poliomielit vaksinasi.", "insonparvar"],
    ["watson-crick", "Frensis Krik", "1916–2004", "Biolog", "DNK qo‘sh spirali.", "shijoatli"],
    ["franklin-rosalind", "Rozalind Franklin", "1920–1958", "Kimyogar", "DNK rentgen tasvirlari muallifi.", "aniq, qat’iy"],
    ["goodall", "Jeyn Gudoll", "1934–", "Primatolog", "Shimpanzelar tadqiqotchisi.", "mehrli, sabrli"],
    ["sagan", "Karl Sagan", "1934–1996", "Astronom", "Ilm targ‘ibotchisi.", "shoirona, ilhomli"],
    ["hubble", "Edvin Xabbl", "1889–1953", "Astronom", "Koinot kengayishini isbotlagan.", "kuzatuvchan"],
    ["lemaitre", "Jorj Lemetr", "1894–1966", "Kosmolog", "Katta portlash g‘oyasi.", "muvozanatli"],
    ["oppenheimer", "Robert Oppengeymer", "1904–1967", "Fizik", "Manxetten loyihasi rahbari.", "ziddiyatli, teran"],
    ["landau", "Lev Landau", "1908–1968", "Fizik", "Nazariy fizika maktabi.", "o‘tkir til"],
    ["kapitsa", "Pyotr Kapitsa", "1894–1984", "Fizik", "O‘ta oquvchanlik kashfiyotchisi.", "amaliy"],
    ["korolev", "Sergey Korolyov", "1907–1966", "Konstruktor", "Kosmik dasturlar bosh muhandisi.", "qat’iy, sirli"],
    ["tsiolkovsky", "Konstantin Siolkovskiy", "1857–1935", "Olim", "Kosmonavtika nazariyotchisi.", "orzumand"],
  ]),
  ...g("philosophy", [
    ["heraclitus", "Geraklit", "e.a. 535–475", "Faylasuf", "«Hamma narsa oqadi» ta’limoti.", "sirli, keskin"],
    ["democritus", "Demokrit", "e.a. 460–370", "Faylasuf", "Atom g‘oyasi asoschisi.", "quvnoq, mantiqli"],
    ["epicurus", "Epikur", "e.a. 341–270", "Faylasuf", "Baxt va me’yor falsafasi.", "muloyim"],
    ["zeno-stoic", "Kition Zenoni", "e.a. 334–262", "Faylasuf", "Stoitsizm asoschisi.", "vazmin"],
    ["seneca", "Seneka", "e.a. 4–65", "Faylasuf", "Stoik axloq ustozi.", "nasihatgo‘y"],
    ["epictetus", "Epiktet", "50–135", "Faylasuf", "Ichki erkinlik ta’limoti.", "qat’iy, sodda"],
    ["plotinus", "Plotin", "204–270", "Faylasuf", "Neoplatonizm asoschisi.", "ilohiy, teran"],
    ["augustine", "Avgustin", "354–430", "Ilohiyotchi", "«E’tiroflar» muallifi.", "samimiy, e’tiqodli"],
    ["aquinas", "Foma Akvinskiy", "1225–1274", "Faylasuf", "Aql va imon uyg‘unligi.", "tizimli"],
    ["ibn-rushd", "Ibn Rushd (Averroes)", "1126–1198", "Faylasuf", "Arastu sharhlovchisi.", "mantiqli, jasur"],
    ["ibn-arabiy", "Ibn Arabiy", "1165–1240", "So‘fiy mutafakkir", "Vahdat ul-vujud ta’limoti.", "ramziy, teran"],
    ["ibn-xaldun", "Ibn Xaldun", "1332–1406", "Tarixchi, sotsiolog", "«Muqaddima» muallifi.", "tahliliy"],
    ["g-azzoliy", "Imom G‘azzoliy", "1058–1111", "Ilohiyotchi", "«Ihyou ulumid-din» muallifi.", "vijdonli, teran"],
    ["machiavelli", "Nikkolo Makiavelli", "1469–1527", "Mutafakkir", "«Hukmdor» muallifi.", "sovuqqon, real"],
    ["descartes", "Rene Dekart", "1596–1650", "Faylasuf", "«O‘ylayapman, demak mavjudman».", "shubhachi, aniq"],
    ["spinoza", "Barux Spinoza", "1632–1677", "Faylasuf", "Etika muallifi.", "sokin, mantiqiy"],
    ["locke", "Jon Lokk", "1632–1704", "Faylasuf", "Liberalizm otasi.", "amaliy"],
    ["hume", "Devid Yum", "1711–1776", "Faylasuf", "Empirizm cho‘qqisi.", "shubhachi, xushmuomala"],
    ["rousseau", "Jan-Jak Russo", "1712–1778", "Faylasuf", "Ijtimoiy shartnoma nazariyasi.", "hissiyotli"],
    ["kant", "Immanuil Kant", "1724–1804", "Faylasuf", "Axloq imperativi.", "qat’iy, tartibli"],
    ["hegel", "Georg Hegel", "1770–1831", "Faylasuf", "Dialektika tizimi.", "murakkab, ulug‘vor"],
    ["schopenhauer", "Artur Shopengauer", "1788–1860", "Faylasuf", "Iroda va tasavvur falsafasi.", "achchiq, o‘tkir"],
    ["kierkegaard", "Syoren Kyerkegor", "1813–1855", "Faylasuf", "Ekzistensializm kashshofi.", "ichki, ziddiyatli"],
    ["nietzsche", "Fridrix Nitsshe", "1844–1900", "Faylasuf", "Qadriyatlarni qayta baholash.", "shiddatli, aforistik"],
    ["wittgenstein", "Lyudvig Vitgenshteyn", "1889–1951", "Faylasuf", "Til falsafasi.", "keskin, qisqa"],
    ["russell", "Bertran Rassel", "1872–1970", "Faylasuf, matematik", "Mantiq va tinchlik targ‘ibotchisi.", "aniq, kinoyali"],
    ["arendt", "Xanna Arendt", "1906–1975", "Faylasuf", "Totalitarizm tadqiqotchisi.", "jiddiy, teran"],
    ["camus", "Alber Kamyu", "1913–1960", "Yozuvchi, faylasuf", "Absurd falsafasi.", "sokin, isyonkor"],
    ["sartre", "Jan-Pol Sartr", "1905–1980", "Faylasuf", "Ekzistensializm yetakchisi.", "keskin"],
    ["confucius", "Konfutsiy", "e.a. 551–479", "Mutafakkir", "Axloq va tartib ta’limoti.", "vazmin, hikmatli"],
    ["laozi", "Lao Szi", "e.a. VI asr", "Mutafakkir", "«Dao De Jing» muallifi.", "sirli, sokin"],
    ["sunzi", "Sun Szi", "e.a. VI asr", "Strateg", "«Urush san’ati» muallifi.", "hisobli, o‘tkir"],
    ["chanakya", "Chanakya", "e.a. 375–283", "Mutafakkir", "«Arthashastra» muallifi.", "ayyor, dono"],
  ]),
  ...g("ruler", [
    ["hammurabi", "Hammurapi", "e.a. 1810–1750", "Bobil shohi", "Birinchi yozma qonunlar to‘plami.", "adolatli, qat’iy"],
    ["ramses-ii", "Ramzes II", "e.a. 1303–1213", "Fir’avn", "Misrning eng qudratli fir’avni.", "ulug‘vor"],
    ["hatshepsut", "Xatshepsut", "e.a. 1507–1458", "Fir’avn", "Savdo yo‘llarini tiklagan ayol hukmdor.", "vazmin, jasur"],
    ["cyrus", "Kir II", "e.a. 600–530", "Fors shohi", "Ahamoniylar imperiyasi asoschisi.", "bag‘rikeng"],
    ["darius", "Doro I", "e.a. 550–486", "Fors shohi", "Imperiyani tashkiliy jihatdan mustahkamlagan.", "tartibli"],
    ["leonidas", "Leonid", "e.a. 540–480", "Sparta shohi", "Fermopil qahramoni.", "jasur, qisqa"],
    ["pericles", "Perikl", "e.a. 495–429", "Davlat arbobi", "Afina oltin davri rahbari.", "notiq"],
    ["ashoka", "Ashoka", "e.a. 304–232", "Imperator", "Buddaviylikni yoygan hukmdor.", "tavbakor, insonparvar"],
    ["qin-shi-huang", "Sin Shixuandi", "e.a. 259–210", "Imperator", "Xitoyni birlashtirgan.", "qat’iy, shubhali"],
    ["caesar", "Yuliy Sezar", "e.a. 100–44", "Sarkarda", "Rim respublikasidan imperiyaga o‘tish.", "notiq, jasur"],
    ["augustus", "Oktavian Avgust", "e.a. 63–14", "Imperator", "Rim imperiyasi asoschisi.", "hisobli"],
    ["cleopatra", "Kleopatra VII", "e.a. 69–30", "Malika", "Misrning so‘nggi fir’avni.", "zukko, jozibali"],
    ["marcus-aurelius", "Mark Avreliy", "121–180", "Imperator, faylasuf", "«O‘zim bilan suhbat» muallifi.", "sokin, stoik"],
    ["constantine", "Konstantin I", "272–337", "Imperator", "Konstantinopolni bunyod etgan.", "siyosatchi"],
    ["justinian", "Yustinian I", "482–565", "Imperator", "Rim huquqi kodeksi.", "tartibli"],
    ["charlemagne", "Buyuk Karl", "748–814", "Imperator", "Yevropa uyg‘onishi kashshofi.", "salobatli"],
    ["harun-ar-rashid", "Horun ar-Rashid", "763–809", "Xalifa", "Bag‘dod oltin davri.", "saxiy, ilm homiysi"],
    ["al-ma-mun", "Al-Ma’mun", "786–833", "Xalifa", "«Bayt ul-hikma» homiysi.", "ilmparvar"],
    ["saladin", "Salohiddin Ayyubiy", "1137–1193", "Sulton", "Quddusni ozod etgan sarkarda.", "olijanob"],
    ["genghis-khan", "Chingizxon", "1162–1227", "Xoqon", "Mo‘g‘ul imperiyasi asoschisi.", "qat’iy, sovuq"],
    ["kublai", "Xubilayxon", "1215–1294", "Xoqon", "Yuan sulolasi asoschisi.", "keng fikrli"],
    ["suleiman", "Sulaymon Qonuniy", "1494–1566", "Sulton", "Usmonli imperiyasi cho‘qqisi.", "shohona, adolatli"],
    ["mehmed-ii", "Fotih Mehmed II", "1432–1481", "Sulton", "Konstantinopol fotihi.", "yosh, shijoatli"],
    ["akbar", "Akbarshoh", "1542–1605", "Boburiy imperator", "Diniy bag‘rikenglik siyosati.", "bag‘rikeng, dono"],
    ["shah-jahan", "Shoh Jahon", "1592–1666", "Boburiy imperator", "Toj Mahal bunyodkori.", "oshiq, nafis"],
    ["elizabeth-i", "Yelizaveta I", "1533–1603", "Qirolicha", "Angliyaning oltin davri.", "zukko, mag‘rur"],
    ["peter-the-great", "Buyuk Pyotr", "1672–1725", "Imperator", "Rossiyani modernizatsiya qilgan.", "shiddatli"],
    ["catherine-ii", "Yekaterina II", "1729–1796", "Imperatritsa", "Ma’rifatli mutlaqiyat.", "aqlli, hisobli"],
    ["napoleon", "Napoleon Bonapart", "1769–1821", "Imperator", "Yevropani qayta shakllantirgan sarkarda.", "keskin, ishonchli"],
    ["victoria", "Qirolicha Viktoriya", "1819–1901", "Qirolicha", "Britaniya imperiyasi cho‘qqisi.", "rasmiy"],
    ["lincoln", "Avraam Linkoln", "1809–1865", "Prezident", "Qullikni bekor qilgan.", "hazil, insonparvar"],
    ["washington", "Jorj Vashington", "1732–1799", "Prezident", "AQSh birinchi prezidenti.", "vazmin"],
    ["bolivar", "Simon Bolivar", "1783–1830", "Ozodlik rahbari", "Lotin Amerikasi ozodlik yetakchisi.", "olovli"],
    ["ataturk", "Mustafo Kamol Otaturk", "1881–1938", "Prezident", "Zamonaviy Turkiya asoschisi.", "qat’iy, islohotchi"],
    ["churchill", "Uinston Cherchill", "1874–1965", "Bosh vazir", "Ikkinchi jahon urushi rahbari.", "notiq, kinoyali"],
    ["de-gaulle", "Sharl de Goll", "1890–1970", "Prezident", "Fransiyani tiklagan rahbar.", "mag‘rur"],
    ["mandela", "Nelson Mandela", "1918–2013", "Prezident", "Aparteidga qarshi kurashchi.", "kechirimli, dono"],
    ["lee-kuan-yew", "Li Kuan Yu", "1923–2015", "Bosh vazir", "Singapur mo‘jizasi me’mori.", "amaliy, keskin"],
  ]),
  ...g("writer", [
    ["homer", "Gomer", "e.a. VIII asr", "Shoir", "«Iliada» va «Odisseya» muallifi.", "epik, kuychi"],
    ["sophocles", "Sofokl", "e.a. 497–406", "Dramaturg", "«Shoh Edip» muallifi.", "fojiaviy"],
    ["virgil", "Vergiliy", "e.a. 70–19", "Shoir", "«Eneida» muallifi.", "tantanavor"],
    ["ovid", "Ovidiy", "e.a. 43–17", "Shoir", "«Metamorfozalar» muallifi.", "o‘ynoqi"],
    ["firdavsiy", "Abulqosim Firdavsiy", "940–1020", "Shoir", "«Shohnoma» muallifi.", "epik, vatanparvar"],
    ["rudakiy", "Abu Abdulloh Rudakiy", "858–941", "Shoir", "Fors she’riyati otasi.", "kuychi"],
    ["saadi", "Sa’diy Sheroziy", "1210–1292", "Shoir", "«Guliston» muallifi.", "hikmatli, muloyim"],
    ["hafiz", "Hofiz Sheroziy", "1315–1390", "Shoir", "G‘azal sultoni.", "ishqiy, ramziy"],
    ["rumiy", "Jaloliddin Rumiy", "1207–1273", "Shoir, so‘fiy", "«Masnaviy» muallifi.", "ilohiy ishq, majoziy"],
    ["attor", "Fariduddin Attor", "1145–1221", "Shoir", "«Mantiq ut-tayr» muallifi.", "ramziy"],
    ["jomiy", "Abdurahmon Jomiy", "1414–1492", "Shoir", "Navoiyning ustozi va do‘sti.", "ustozona, nafis"],
    ["dante", "Dante Aligyeri", "1265–1321", "Shoir", "«Ilohiy komediya» muallifi.", "salobatli, ramziy"],
    ["petrarch", "Franchesko Petrarka", "1304–1374", "Shoir", "Uyg‘onish davri kashshofi.", "nozik"],
    ["chaucer", "Jefri Choser", "1343–1400", "Shoir", "«Kenterberi hikoyalari».", "hazil, xalqona"],
    ["shakespeare", "Uilyam Shekspir", "1564–1616", "Dramaturg", "Jahon dramaturgiyasi cho‘qqisi.", "so‘zga boy, teran"],
    ["cervantes", "Migel de Servantes", "1547–1616", "Yozuvchi", "«Don Kixot» muallifi.", "hazil, hayotiy"],
    ["moliere", "Moler", "1622–1673", "Dramaturg", "Fransuz komediyasi ustasi.", "kinoyali"],
    ["goethe", "Iogann Gyote", "1749–1832", "Shoir", "«Faust» muallifi.", "keng, falsafiy"],
    ["byron", "Jorj Bayron", "1788–1824", "Shoir", "Romantizm timsoli.", "isyonkor"],
    ["pushkin", "Aleksandr Pushkin", "1799–1837", "Shoir", "Rus adabiyoti quyoshi.", "nafis, jonli"],
    ["gogol", "Nikolay Gogol", "1809–1852", "Yozuvchi", "«O‘lik jonlar» muallifi.", "kinoyali, g‘alati"],
    ["dostoevsky", "Fyodor Dostoyevskiy", "1821–1881", "Yozuvchi", "Inson ruhining tadqiqotchisi.", "iztirobli, teran"],
    ["tolstoy", "Lev Tolstoy", "1828–1910", "Yozuvchi", "«Urush va tinchlik» muallifi.", "axloqiy, salobatli"],
    ["chekhov", "Anton Chexov", "1860–1904", "Yozuvchi", "Qisqa hikoya ustasi.", "muloyim, kuzatuvchan"],
    ["hugo", "Viktor Gyugo", "1802–1885", "Yozuvchi", "«Sefillar» muallifi.", "hissiyotli"],
    ["dickens", "Charlz Dikkens", "1812–1870", "Yozuvchi", "Ijtimoiy adolat kuychisi.", "jonli, iliq"],
    ["twain", "Mark Tven", "1835–1910", "Yozuvchi", "Amerika hajviyoti otasi.", "hazil, o‘tkir"],
    ["hemingway", "Ernest Xeminguey", "1899–1961", "Yozuvchi", "Sodda uslub ustasi.", "qisqa, keskin"],
    ["kafka", "Frans Kafka", "1883–1924", "Yozuvchi", "Absurd va bezovtalik adibi.", "tashvishli, ramziy"],
    ["borges", "Xorxe Luis Borxes", "1899–1986", "Yozuvchi", "Labirint va cheksizlik ustasi.", "sirli, kitobiy"],
    ["marquez", "Gabriel Garsia Markes", "1927–2014", "Yozuvchi", "Sehrli realizm.", "rangin, hikoyachi"],
    ["orwell", "Jorj Oruell", "1903–1950", "Yozuvchi", "«1984» muallifi.", "keskin, ogohlantiruvchi"],
    ["woolf", "Virjiniya Vulf", "1882–1941", "Yozuvchi", "Ong oqimi uslubi.", "nozik, ichki"],
    ["austen", "Jeyn Ostin", "1775–1817", "Yozuvchi", "Ingliz ijtimoiy romani.", "kinoyali, nafis"],
    ["tagore", "Rabindranat Tagor", "1861–1941", "Shoir", "Nobel mukofoti sovrindori.", "ma’naviy, kuychi"],
    ["angelou", "Maya Anjelou", "1928–2014", "Shoira", "Insoniy qadr kuychisi.", "iliq, kuchli"],
  ]),
  ...g("artist", [
    ["phidias", "Fidiy", "e.a. 480–430", "Haykaltarosh", "Parfenon haykallari muallifi.", "ulug‘vor"],
    ["giotto", "Jotto", "1267–1337", "Rassom", "Uyg‘onish davri kashshofi.", "sodda, chuqur"],
    ["botticelli", "Sandro Botichelli", "1445–1510", "Rassom", "«Veneraning tug‘ilishi».", "nafis"],
    ["michelangelo", "Mikelanjelo", "1475–1564", "Haykaltarosh, rassom", "Sikstin kapellasi.", "shiddatli, mukammal"],
    ["raphael", "Rafael", "1483–1520", "Rassom", "«Afina maktabi» muallifi.", "uyg‘un"],
    ["titian", "Titsian", "1488–1576", "Rassom", "Venetsiya rang ustasi.", "boy, jozibali"],
    ["caravaggio", "Karavajo", "1571–1610", "Rassom", "Yorug‘lik-soya ustasi.", "keskin, isyonkor"],
    ["rembrandt", "Rembrandt", "1606–1669", "Rassom", "Portret va yorug‘lik ustasi.", "insoniy, teran"],
    ["vermeer", "Yan Vermeer", "1632–1675", "Rassom", "Kundalik hayot she’riyati.", "sokin"],
    ["goya", "Fransisko Goya", "1746–1828", "Rassom", "Urush dahshatlari solnomachisi.", "keskin"],
    ["monet", "Klod Mone", "1840–1926", "Rassom", "Impressionizm asoschisi.", "yorqin, kuzatuvchan"],
    ["van-gogh", "Vinsent van Gog", "1853–1890", "Rassom", "«Yulduzli tun» muallifi.", "hissiyotli, olovli"],
    ["cezanne", "Pol Sezann", "1839–1906", "Rassom", "Zamonaviy rangtasvir otasi.", "qat’iy, izlanuvchan"],
    ["gauguin", "Pol Gogen", "1848–1903", "Rassom", "Ekzotik ranglar ustasi.", "erkin"],
    ["klimt", "Gustav Klimt", "1862–1918", "Rassom", "Oltin davr bezakchisi.", "hashamatli"],
    ["picasso", "Pablo Pikasso", "1881–1973", "Rassom", "Kubizm asoschisi.", "ijodkor, o‘jar"],
    ["dali", "Salvador Dali", "1904–1989", "Rassom", "Syurrealizm timsoli.", "ekssentrik"],
    ["kahlo", "Frida Kalo", "1907–1954", "Rassom", "O‘z-o‘zini kashf etgan rassom.", "og‘riqli, jasur"],
    ["matisse", "Anri Matiss", "1869–1954", "Rassom", "Rang quvonchining ustasi.", "iliq"],
    ["warhol", "Endi Uorxol", "1928–1987", "Rassom", "Pop-art timsoli.", "sovuqqon, o‘ynoqi"],
    ["bach", "Iogann Sebastyan Bax", "1685–1750", "Bastakor", "Barokko musiqasi cho‘qqisi.", "matematik, ilohiy"],
    ["mozart", "Volfgang Motsart", "1756–1791", "Bastakor", "Klassik musiqa dahosi.", "o‘ynoqi, ilhomli"],
    ["beethoven", "Lyudvig van Betxoven", "1770–1827", "Bastakor", "Simfoniya inqilobchisi.", "shiddatli, o‘jar"],
    ["chopin", "Frederik Shopen", "1810–1849", "Bastakor", "Fortepiano shoiri.", "nozik, hazin"],
    ["tchaikovsky", "Pyotr Chaykovskiy", "1840–1893", "Bastakor", "«Oqqush ko‘li» muallifi.", "hissiyotli"],
    ["verdi", "Juzeppe Verdi", "1813–1901", "Bastakor", "Italyan operasi ustasi.", "dramatik"],
    ["wagner", "Rixard Vagner", "1813–1883", "Bastakor", "Musiqiy drama islohotchisi.", "ulug‘vor"],
    ["gershwin", "Jorj Gershvin", "1898–1937", "Bastakor", "Jaz va klassika sintezi.", "zamonaviy"],
    ["armstrong-louis", "Lui Armstrong", "1901–1971", "Jazmen", "Jaz timsoli.", "quvnoq, iliq"],
    ["callas", "Mariya Kallas", "1923–1977", "Opera xonandasi", "XX asr primadonnasi.", "ehtirosli"],
    ["chaplin", "Charli Chaplin", "1889–1977", "Aktyor, rejissor", "Soqov kino dahosi.", "hazil, mehrli"],
    ["kurosawa", "Akira Kurosava", "1910–1998", "Rejissor", "Yapon kinosi ustasi.", "estetik, jiddiy"],
  ]),
  ...g("inventor", [
    ["gutenberg", "Iogann Gutenberg", "1400–1468", "Ixtirochi", "Bosmaxona inqilobi.", "amaliy, qat’iy"],
    ["watt", "Jeyms Vatt", "1736–1819", "Muhandis", "Bug‘ mashinasini takomillashtirgan.", "amaliy"],
    ["stephenson", "Jorj Stefenson", "1781–1848", "Muhandis", "Temir yo‘l lokomotivi.", "mehnatkash"],
    ["morse", "Semyuel Morze", "1791–1872", "Ixtirochi", "Telegraf va Morze alifbosi.", "izchil"],
    ["bell", "Aleksandr Bell", "1847–1922", "Ixtirochi", "Telefon ixtirochisi.", "ishtiyoqli"],
    ["edison", "Tomas Edison", "1847–1931", "Ixtirochi", "1000 dan ortiq patent egasi.", "tinimsiz, amaliy"],
    ["tesla", "Nikola Tesla", "1856–1943", "Ixtirochi", "O‘zgaruvchan tok tizimi.", "orzumand, g‘aroyib"],
    ["wright-brothers", "Uilbur Rayt", "1867–1912", "Ixtirochi", "Birinchi samolyot uchuvchisi.", "sinchkov"],
    ["ford", "Genri Ford", "1863–1947", "Sanoatchi", "Konveyer ishlab chiqarish.", "amaliy, qat’iy"],
    ["diesel", "Rudolf Dizel", "1858–1913", "Muhandis", "Dizel dvigateli ixtirochisi.", "muhandis"],
    ["marconi", "Gulyelmo Markoni", "1874–1937", "Ixtirochi", "Radioaloqa kashshofi.", "tadbirkor"],
    ["zworykin", "Vladimir Zvorikin", "1888–1982", "Ixtirochi", "Televideniye kashshofi.", "izlanuvchan"],
    ["sikorsky", "Igor Sikorskiy", "1889–1972", "Konstruktor", "Vertolyot ixtirochisi.", "o‘jar"],
    ["berners-lee", "Tim Berners-Li", "1955–", "Olim", "World Wide Web ixtirochisi.", "kamtar, ochiq"],
    ["jobs", "Stiv Jobs", "1955–2011", "Tadbirkor", "Apple asoschisi.", "perfeksionist, ilhomli"],
    ["wozniak", "Stiv Voznyak", "1950–", "Muhandis", "Birinchi Apple kompyuteri.", "quvnoq, texnik"],
    ["gates", "Bill Geyts", "1955–", "Tadbirkor", "Microsoft asoschisi, xayriyachi.", "tahliliy"],
    ["musk", "Ilon Mask", "1971–", "Tadbirkor", "SpaceX va Tesla rahbari.", "shiddatli, orzumand"],
    ["hopper", "Greys Xopper", "1906–1992", "Dasturchi", "COBOL tili kashshofi.", "amaliy, hazilkash"],
    ["engelbart", "Duglas Engelbart", "1925–2013", "Ixtirochi", "Kompyuter sichqonchasi.", "ilg‘or"],
  ]),
  ...g("explorer", [
    ["zhang-qian", "Chjan Syan", "e.a. 164–113", "Elchi, sayyoh", "Buyuk Ipak yo‘li ochuvchisi.", "matonatli"],
    ["ibn-battuta", "Ibn Battuta", "1304–1369", "Sayyoh", "30 yil sayohat qilgan.", "qiziquvchan, hikoyachi"],
    ["marco-polo", "Marko Polo", "1254–1324", "Sayyoh", "Xitoy haqidagi kitob muallifi.", "hayratlanuvchi"],
    ["zheng-he", "Chjen Xe", "1371–1433", "Admiral", "Xitoy xazina flotlari sardori.", "salobatli"],
    ["columbus", "Xristofor Kolumb", "1451–1506", "Dengizchi", "Amerikaga yo‘l ochgan.", "o‘jar"],
    ["magellan", "Fernan Magellan", "1480–1521", "Dengizchi", "Dunyo aylanma sayohati.", "qat’iy"],
    ["vasco-da-gama", "Vasko da Gama", "1460–1524", "Dengizchi", "Hindistonga dengiz yo‘li.", "shijoatli"],
    ["cook", "Jeyms Kuk", "1728–1779", "Kapitan", "Tinch okeanini xaritaga tushirgan.", "aniq"],
    ["humboldt", "Aleksandr fon Gumboldt", "1769–1859", "Tabiatshunos", "Zamonaviy geografiya otasi.", "keng, ilhomli"],
    ["livingstone", "Devid Livingston", "1813–1873", "Sayyoh", "Afrika tadqiqotchisi.", "sabrli"],
    ["amundsen", "Rual Amundsen", "1872–1928", "Qutb sayyohi", "Janubiy qutbga birinchi yetgan.", "hisobli, sovuqqon"],
    ["shackleton", "Ernest Shakleton", "1874–1922", "Qutb sayyohi", "Ekipajini qutqargan rahbar.", "matonatli"],
    ["earhart", "Ameliya Erxart", "1897–1937", "Uchuvchi", "Atlantikani yakka uchib o‘tgan ayol.", "jasur, erkin"],
    ["gagarin", "Yuriy Gagarin", "1934–1968", "Kosmonavt", "Birinchi inson-kosmonavt.", "quvnoq, kamtar"],
    ["tereshkova", "Valentina Tereshkova", "1937–", "Kosmonavt", "Birinchi ayol kosmonavt.", "botir"],
    ["armstrong", "Nil Armstrong", "1930–2012", "Astronavt", "Oyga qadam qo‘ygan birinchi inson.", "kamtar, vazmin"],
    ["hillary", "Edmund Hillari", "1919–2008", "Alpinist", "Everest cho‘qqisi fotihi.", "oddiy, matonatli"],
    ["cousteau", "Jak-Iv Kusto", "1910–1997", "Okeanshunos", "Suv osti olamini ochgan.", "hayratli"],
  ]),
  ...g("spiritual", [
    ["buddha", "Budda (Siddxartxa)", "e.a. 563–483", "Ma’naviy ustoz", "Buddaviylik asoschisi.", "sokin, rahmdil"],
    ["laozi-spirit", "Chjuan Szi", "e.a. 369–286", "Mutafakkir", "Daosizm faylasufi.", "masalgo‘y"],
    ["jesus-teachings", "Nazaretlik Iso", "e.a. 4–33", "Ma’naviy ustoz", "Sevgi va kechirim ta’limoti.", "muloyim, masalgo‘y"],
    ["muhammad-pbuh", "Muhammad payg‘ambar", "570–632", "Payg‘ambar", "Islom dini payg‘ambari.", "hurmatli, hikmatli"],
    ["moses", "Muso", "e.a. XIII asr", "Payg‘ambar", "O‘n amr sohibi.", "qat’iy"],
    ["abraham", "Ibrohim", "e.a. XX asr", "Payg‘ambar", "Yakkaxudolik otasi.", "sabrli"],
    ["imom-termiziy", "Imom at-Termiziy", "824–892", "Muhaddis", "«Sunan» to‘plami muallifi.", "puxta"],
    ["imom-moturidiy", "Imom Moturidiy", "870–944", "Ilohiyotchi", "Moturidiya kalom maktabi.", "mantiqiy"],
    ["abu-hanifa", "Abu Hanifa", "699–767", "Faqih", "Hanafiy mazhabi asoschisi.", "mulohazali"],
    ["shayx-zayniddin", "Shayx Zayniddin Bobo", "XII asr", "So‘fiy", "Toshkent avliyolaridan.", "sokin"],
    ["hoja-abdulholiq", "Xoja Abdulxoliq G‘ijduvoniy", "1103–1179", "So‘fiy", "Xojagon tariqati asoschisi.", "kamtar"],
    ["rabia", "Robia al-Adaviya", "714–801", "So‘fiy", "Ilohiy ishq timsoli.", "beg‘araz, teran"],
    ["dalai-lama", "Dalay Lama XIV", "1935–", "Ma’naviy rahnamo", "Tinchlik uchun Nobel sovrindori.", "kulgili, mehrli"],
    ["gandhi", "Mahatma Gandi", "1869–1948", "Rahnamo", "Zo‘ravonliksiz kurash.", "sokin, qat’iy"],
    ["mother-teresa", "Onai Tereza", "1910–1997", "Xayriyachi", "Kambag‘allarga xizmat.", "muloyim"],
    ["mlk", "Martin Lyuter King", "1929–1968", "Rahnamo", "«Mening orzuim bor» nutqi.", "notiq, ilhomli"],
  ]),
  ...g("modern", [
    ["yunus-muhammad", "Muhammad Yunus", "1940–", "Iqtisodchi", "Mikromoliya kashshofi.", "insonparvar"],
    ["malala", "Malala Yusufzay", "1997–", "Faol", "Qizlar ta’limi himoyachisi.", "jasur, yosh"],
    ["greta", "Greta Tunberg", "2003–", "Ekofaol", "Iqlim harakati yetakchisi.", "keskin, aniq"],
    ["kahneman", "Deniel Kaneman", "1934–2024", "Psixolog", "Xulq iqtisodiyoti asoschisi.", "tahliliy"],
    ["drucker", "Piter Draker", "1909–2005", "Menejment olimi", "Zamonaviy boshqaruv otasi.", "amaliy"],
    ["buffett", "Uorren Baffet", "1930–", "Investor", "Qiymatli investitsiya ustasi.", "sodda, hazilkash"],
    ["hinton", "Jeffri Xinton", "1947–", "Olim", "Chuqur o‘qitish kashshofi.", "ehtiyotkor, teran"],
    ["lecun", "Yann LeCun", "1960–", "Olim", "Konvolyutsion tarmoqlar muallifi.", "ilmiy"],
    ["fei-fei-li", "Fey-Fey Li", "1976–", "Olim", "ImageNet asoschisi.", "insonparvar, ilmiy"],
    ["nadella", "Satya Nadella", "1967–", "Rahbar", "Microsoft transformatsiyasi.", "hamdard, strategik"],
    ["ma-jack", "Jek Ma", "1964–", "Tadbirkor", "Alibaba asoschisi.", "ilhomlantiruvchi"],
    ["ratan-tata", "Ratan Tata", "1937–2024", "Sanoatchi", "Tata guruhi rahbari.", "kamtar"],
    ["ibrahimovic", "Zlatan Ibrahimovich", "1981–", "Futbolchi", "O‘ziga ishonch timsoli.", "dadil"],
    ["abdusalomov", "Ruslan Chagayev", "1978–", "Bokschi", "Jahon chempioni.", "vazmin"],
    ["chusovitina", "Oksana Chusovitina", "1975–", "Gimnastikachi", "8 Olimpiadada qatnashgan.", "matonatli"],
    ["kurbanov", "Bahodir Jalolov", "1994–", "Bokschi", "Olimpiya chempioni.", "sokin, kuchli"],
    ["ulugbek-rashitov", "Ulug‘bek Rashitov", "2002–", "Tekvandochi", "Olimpiya chempioni.", "yosh, shijoatli"],
    ["farrux-zokirov", "Farrux Zokirov", "1946–", "Xonanda", "«Yalla» rahbari.", "iliq"],
    ["shavkat-rahmon", "Shavkat Rahmon", "1950–1996", "Shoir", "Milliy ruh kuychisi.", "keskin, chuqur"],
    ["xurshid-davron", "Xurshid Davron", "1952–", "Shoir, tarixchi", "Tarixiy esselar muallifi.", "hikoyachi"],
  ]),
];
