import amirTemur from "@/assets/amir-temur.jpg";
import alKhwarizmi from "@/assets/al-khwarizmi.jpg";
import ulugbek from "@/assets/ulugbek.jpg";

export type FigureCategory =
  | "uzbek"
  | "science"
  | "philosophy"
  | "ruler"
  | "writer"
  | "artist"
  | "inventor"
  | "modern"
  | "explorer"
  | "spiritual";

export const CATEGORY_LABELS: Record<FigureCategory, string> = {
  uzbek: "O‘zbek / Markaziy Osiyo",
  science: "Ilm-fan",
  philosophy: "Falsafa",
  ruler: "Hukmdorlar",
  writer: "Yozuvchi & Shoir",
  artist: "San’atkor",
  inventor: "Ixtirochi",
  modern: "Zamonaviy",
  explorer: "Sayyoh & Kashfiyotchi",
  spiritual: "Ma’naviyat",
};

export type Figure = {
  id: string;
  name: string;
  era: string;
  role: string;
  bio: string;
  category: FigureCategory;
  image?: string;
  voiceHint: string; // for nutq uslubi
  featured?: boolean;
};

const f = (
  id: string,
  name: string,
  era: string,
  role: string,
  bio: string,
  category: FigureCategory,
  voiceHint: string,
  extra?: Partial<Figure>,
): Figure => ({ id, name, era, role, bio, category, voiceHint, ...extra });

export const FIGURES: Figure[] = [
  // ====== FEATURED — O‘zbek / Markaziy Osiyo ======
  f("amir-temur", "Amir Temur", "1336–1405", "Sohibqiron, davlat arbobi",
    "Temuriylar saltanati asoschisi. Samarqandni jahon poytaxtiga aylantirgan.",
    "uzbek", "amrkorona, dono, strategik, qudratli",
    { image: amirTemur, featured: true }),
  f("al-khwarizmi", "Al-Xorazmiy", "780–850", "Matematik, astronom",
    "Algebra va algoritm fanlarining otasi.",
    "science", "bilimdon, xotirjam, mantiqiy",
    { image: alKhwarizmi, featured: true }),
  f("ulugbek", "Mirzo Ulug‘bek", "1394–1449", "Astronom, hukmdor",
    "Samarqand rasadxonasi quruvchisi, yulduzlar jadvali muallifi.",
    "uzbek", "olijanob, ilmiy, mehribon",
    { image: ulugbek, featured: true }),

  f("ibn-sino", "Abu Ali ibn Sino", "980–1037", "Tabib, faylasuf",
    "“Tib qonunlari” muallifi, jahon tibbiyotining otasi.",
    "science", "donishmand, sabrli, tahliliy"),
  f("al-beruni", "Abu Rayhon Beruniy", "973–1048", "Qomusiy olim",
    "Geografiya, astronomiya va tarix bo‘yicha ulkan asarlar muallifi.",
    "science", "qiziquvchan, aniq, keng qamrovli"),
  f("al-farabi", "Abu Nasr Forobiy", "872–950", "Faylasuf",
    "Arastudan keyingi “Ikkinchi muallim”.",
    "philosophy", "tafakkurli, ohista, fasohatli"),
  f("alisher-navoiy", "Alisher Navoiy", "1441–1501", "Shoir, davlat arbobi",
    "O‘zbek adabiy tilining asoschisi.",
    "writer", "she’riy, latif, hikmatli"),
  f("bobur", "Zahiriddin Muhammad Bobur", "1483–1530", "Shoh, shoir",
    "Boburiylar saltanati asoschisi, “Boburnoma” muallifi.",
    "ruler", "samimiy, jasur, lirik"),
  f("imam-bukhari", "Imom Buxoriy", "810–870", "Muhaddis",
    "“Sahih al-Buxoriy” muallifi.",
    "spiritual", "vazmin, taqvodor, aniq"),
  f("imam-termiziy", "Imom at-Termiziy", "824–892", "Muhaddis",
    "Hadis ilmining buyuk allomasi.",
    "spiritual", "muloyim, ilmli, samimiy"),
  f("ahmad-yassaviy", "Xoja Ahmad Yassaviy", "1093–1166", "Sufiy, shoir",
    "“Devoni hikmat” muallifi.",
    "spiritual", "hikmatli, ruhoniy, mehrli"),
  f("bahouddin-naqshband", "Bahouddin Naqshband", "1318–1389", "Sufiy",
    "Naqshbandiya tariqati asoschisi.",
    "spiritual", "tinch, dilkash, oddiy"),
  f("mahmud-koshgariy", "Mahmud Koshg‘ariy", "1029–1101", "Tilshunos",
    "“Devonu lug‘otit-turk” muallifi.",
    "writer", "qiziquvchan, etnograf, sayyoh"),
  f("yusuf-balasaguniy", "Yusuf Xos Hojib", "1019–1085", "Shoir",
    "“Qutadg‘u bilig” dostoni muallifi.",
    "writer", "axloqiy, donishmand"),
  f("mashrab", "Boborahim Mashrab", "1640–1711", "Sufiy shoir",
    "Erkparvar va isyonkor shoir.",
    "writer", "ehtirosli, ozodlik istovchi"),
  f("ogahi", "Muhammad Rizo Ogahiy", "1809–1874", "Shoir, tarixchi",
    "Xorazm tarixnavisi.",
    "writer", "vazmin, tarixiy"),
  f("furqat", "Zokirjon Furqat", "1859–1909", "Ma’rifatparvar shoir",
    "Yangilik va ilm targ‘ibotchisi.",
    "writer", "ma’rifatli, kuyunchak"),
  f("muqimi", "Muhammad Aminxoja Muqimiy", "1850–1903", "Shoir",
    "Demokratik she’riyat namoyandasi.",
    "writer", "hajviy, xalqchil"),
  f("cholpon", "Abdulhamid Cho‘lpon", "1897–1938", "Shoir",
    "Jadid harakatining buyuk namoyandasi.",
    "writer", "ozodlikparvar, lirik"),
  f("fitrat", "Abdurauf Fitrat", "1886–1938", "Olim, dramaturg",
    "Jadid mafkurachisi.",
    "writer", "tahliliy, kurashchan"),
  f("qodiriy", "Abdulla Qodiriy", "1894–1938", "Yozuvchi",
    "“O‘tkan kunlar” muallifi.",
    "writer", "obrazli, milliy"),
  f("oybek", "Oybek (Musa Toshmuhammad o‘g‘li)", "1905–1968", "Yozuvchi",
    "“Navoiy” romani muallifi.",
    "writer", "epik, tarixiy"),
  f("gafur-gulom", "G‘afur G‘ulom", "1903–1966", "Shoir",
    "Zamonaviy o‘zbek she’riyati ustasi.",
    "writer", "issiq, xalqchil"),
  f("zulfiya", "Zulfiya Isroilova", "1915–1996", "Shoira",
    "O‘zbek shoiralarining yorqin vakili.",
    "writer", "lirik, nozik"),
  f("erkin-vohidov", "Erkin Vohidov", "1936–2016", "Shoir",
    "“Ruhlar isyoni” muallifi.",
    "writer", "vatanparvar, ehtirosli"),
  f("abdulla-oripov", "Abdulla Oripov", "1941–2016", "Shoir",
    "O‘zbekiston madhiyasi muallifi.",
    "writer", "milliy, jiddiy"),
  f("munavvar-qori", "Munavvar Qori Abdurashidxonov", "1878–1931", "Jadid",
    "Yangi usul maktablari asoschisi.",
    "modern", "ma’rifatchi, izlanuvchan"),
  f("behbudiy", "Mahmudxo‘ja Behbudiy", "1875–1919", "Jadid",
    "“Padarkush” dramasi muallifi.",
    "modern", "ma’rifatchi, kuyunchak"),
  f("ulug-namangani", "Hamza Hakimzoda Niyoziy", "1889–1929", "Shoir",
    "Yangi davr o‘zbek dramaturgiyasi asoschisi.",
    "writer", "kurashchan, xalqchil"),
  f("usmon-nosir", "Usmon Nosir", "1912–1944", "Shoir",
    "Yosh romantik shoir.",
    "writer", "ehtirosli, isyonkor"),
  f("hamid-olimjon", "Hamid Olimjon", "1909–1944", "Shoir",
    "Romantik she’riyat ustasi.",
    "writer", "nafis, ohangdor"),
  f("uygun", "Uyg‘un", "1905–1990", "Dramaturg",
    "O‘zbek dramaturgiyasi yetakchisi.",
    "writer", "teatrlash, qiziquvchan"),
  f("kamil-yashin", "Komil Yashin", "1909–1997", "Dramaturg",
    "“Nurxon” muallifi.",
    "writer", "tarixiy, sahnaviy"),
  f("said-ahmad", "Said Ahmad", "1920–2007", "Yozuvchi",
    "“Kelinlar qo‘zg‘oloni” muallifi.",
    "writer", "hazil, donishmand"),
  f("tohir-malik", "Tohir Malik", "1946–2019", "Yozuvchi",
    "Detektiv janr ustasi.",
    "writer", "sirli, axloqiy"),
  f("o-yoqubov", "Odil Yoqubov", "1926–2009", "Yozuvchi",
    "“Ulug‘bek xazinasi” muallifi.",
    "writer", "tarixiy, falsafiy"),
  f("pirimqul-qodirov", "Pirimqul Qodirov", "1928–2010", "Yozuvchi",
    "“Yulduzli tunlar” muallifi.",
    "writer", "epik, vazmin"),
  f("shukur-xolmirzaev", "Shukur Xolmirzaev", "1940–2005", "Yozuvchi",
    "Tog‘ qishloqlari obrazlari ustasi.",
    "writer", "tabiatga yaqin"),
  f("muhammad-yusuf", "Muhammad Yusuf", "1954–2001", "Shoir",
    "“Onajon” muallifi.",
    "writer", "mehrli, oddiy"),
  f("xurshid-davron", "Xurshid Davron", "1952–", "Shoir",
    "Tarixiy she’riyat ustasi.",
    "writer", "tarixiy, ramziy"),
  f("rauf-parfi", "Rauf Parfi", "1943–2005", "Shoir",
    "Modern o‘zbek she’riyatining yangilovchisi.",
    "writer", "intellektual, falsafiy"),
  f("sharaf-rashidov", "Sharof Rashidov", "1917–1983", "Davlat arbobi, yozuvchi",
    "O‘zbekiston rahbari, “G‘oliblar” muallifi.",
    "ruler", "viqorli, vazmin"),
  f("islom-karimov", "Islom Karimov", "1938–2016", "Birinchi Prezident",
    "Mustaqil O‘zbekistonning birinchi prezidenti.",
    "modern", "qat’iy, davlatchi"),
  f("jaloliddin-manguberdi", "Jaloliddin Manguberdi", "1199–1231", "Sarkarda",
    "Xorazmshohlar davlatining oxirgi mardonavar himoyachisi.",
    "ruler", "jasur, otashin"),
  f("temur-malik", "Temur Malik", "?–1229", "Sarkarda",
    "Xo‘jand qahramoni.",
    "ruler", "mardonavor, kamtar"),
  f("shayboniy-khan", "Muhammad Shayboniyxon", "1451–1510", "Hukmdor",
    "Shayboniylar sulolasi asoschisi.",
    "ruler", "qat’iy, sulolaviy"),
  f("abulhayrxon", "Abulxayrxon", "1412–1468", "Hukmdor",
    "Ko‘chmanchi o‘zbeklar davlati asoschisi.",
    "ruler", "qudratli, sarkarda"),
  f("xudoyorxon", "Xudoyorxon", "1829–1882", "Qo‘qon xoni",
    "Qo‘qon xonligining so‘nggi taniqli hukmdori.",
    "ruler", "saroyga xos, nozik"),
  f("nodirabegim", "Nodirabegim", "1792–1842", "Shoira, hukmdor",
    "Qo‘qon malikasi, davlat arbobi.",
    "ruler", "donishmand, she’riy"),
  f("uvaysiy", "Jahon Otin Uvaysiy", "1781–1845", "Shoira",
    "Qo‘qon adabiy muhitining mashhur shoirasi.",
    "writer", "ma’naviy, nozik"),
  f("mashrab-ii", "Sayyid Qosimiy", "1374–1432", "Shoir",
    "Hurufiy shoir.",
    "writer", "ramziy, sirli"),

  // ====== Jahon ilm-fani ======
  f("einstein", "Albert Eynshteyn", "1879–1955", "Fizik",
    "Nisbiylik nazariyasi muallifi.",
    "science", "ijodkor, tafakkurli, hazilkash"),
  f("newton", "Isaak Nyuton", "1643–1727", "Fizik, matematik",
    "Klassik mexanika asoschisi.",
    "science", "qat’iy, tahliliy"),
  f("galileo", "Galileo Galiley", "1564–1642", "Astronom",
    "Zamonaviy ilmiy uslub asoschisi.",
    "science", "izlanuvchan, jasur"),
  f("darwin", "Charlz Darvin", "1809–1882", "Tabiatshunos",
    "Evolyutsiya nazariyasi muallifi.",
    "science", "sabrli, kuzatuvchan"),
  f("tesla", "Nikola Tesla", "1856–1943", "Ixtirochi",
    "O‘zgaruvchan tok va ko‘plab ixtirolar muallifi.",
    "inventor", "ehtirosli, kelajakparvar"),
  f("edison", "Tomas Edison", "1847–1931", "Ixtirochi",
    "1000+ patentga ega ixtirochi.",
    "inventor", "amaliy, mehnatsevar"),
  f("curie", "Mariya Kyuri", "1867–1934", "Fizik, kimyogar",
    "Ikki Nobel mukofoti sohibasi.",
    "science", "sabotli, jiddiy"),
  f("hawking", "Stiven Xoking", "1942–2018", "Astrofizik",
    "Qora tuynuklar nazariyasi.",
    "science", "hazilkash, chuqur"),
  f("feynman", "Richard Feynman", "1918–1988", "Fizik",
    "Kvant elektrodinamikasi.",
    "science", "qiziquvchan, samimiy"),
  f("turing", "Alan Tyuring", "1912–1954", "Matematik",
    "Kompyuter ilmining otasi.",
    "science", "tafakkurli, yolg‘iz"),
  f("vonneumann", "Jon fon Neyman", "1903–1957", "Matematik",
    "Kompyuter arxitekturasi asoschisi.",
    "science", "tezkor, polimat"),
  f("euler", "Leonard Eyler", "1707–1783", "Matematik",
    "Tarixning eng samarali matematigi.",
    "science", "tartibli, chuqur"),
  f("gauss", "Karl Fridrix Gauss", "1777–1855", "Matematik",
    "“Matematiklar shoshasi”.",
    "science", "puxta, sokin"),
  f("riemann", "Bernxard Riman", "1826–1866", "Matematik",
    "Riman geometriyasi muallifi.",
    "science", "tafakkurli, asabiy"),
  f("hilbert", "David Gilbert", "1862–1943", "Matematik",
    "20 muammoning muallifi.",
    "science", "tizimli, qat’iy"),
  f("ramanujan", "Srinivasa Ramanujan", "1887–1920", "Matematik",
    "Sehrli intuitiv matematik.",
    "science", "intuitiv, mo‘jizakor"),
  f("pasteur", "Lui Paster", "1822–1895", "Mikrobiolog",
    "Vaktsina va pasterizatsiya.",
    "science", "mehnatkash, insonparvar"),
  f("mendeleev", "Dmitriy Mendeleev", "1834–1907", "Kimyogar",
    "Davriy jadval muallifi.",
    "science", "tizimli, izchil"),
  f("lavoisier", "Antuan Lavuazye", "1743–1794", "Kimyogar",
    "Zamonaviy kimyo asoschisi.",
    "science", "aniq, tartibli"),
  f("kepler", "Iogann Kepler", "1571–1630", "Astronom",
    "Sayyoralar harakati qonunlari.",
    "science", "ilohiy uyg‘unlik izlovchi"),
  f("copernicus", "Nikolay Kopernik", "1473–1543", "Astronom",
    "Geliotsentrik tizim muallifi.",
    "science", "vazmin, jasur"),
  f("aristotle", "Aristotel", "384–322 mil. av.", "Faylasuf",
    "G‘arb falsafasining ustozi.",
    "philosophy", "tartibli, hammasini tasniflovchi"),
  f("plato", "Aflotun", "428–348 mil. av.", "Faylasuf",
    "Akademiya asoschisi.",
    "philosophy", "savol-javobli, badiiy"),
  f("socrates", "Suqrot", "470–399 mil. av.", "Faylasuf",
    "Maieutika usulining otasi.",
    "philosophy", "savolga undovchi, kamtar"),
  f("confucius", "Konfutsiy", "551–479 mil. av.", "Faylasuf",
    "Xitoy axloq falsafasi.",
    "philosophy", "hikmatli, vazmin"),
  f("laotzu", "Lao Szi", "VI asr mil. av.", "Faylasuf",
    "Daosizm asoschisi.",
    "philosophy", "sirli, sokin"),
  f("buddha", "Gautama Budda", "563–483 mil. av.", "Ma’naviy ustoz",
    "Buddizm asoschisi.",
    "spiritual", "tinch, mehrli"),
  f("descartes", "Rene Dekart", "1596–1650", "Faylasuf",
    "“O‘ylayman, demak, mavjudman”.",
    "philosophy", "tahliliy, shubhachi"),
  f("kant", "Immanuil Kant", "1724–1804", "Faylasuf",
    "“Sof aql tanqidi” muallifi.",
    "philosophy", "qat’iy, tartibli"),
  f("hegel", "Georg Hegel", "1770–1831", "Faylasuf",
    "Dialektika.",
    "philosophy", "murakkab, tizimli"),
  f("nietzsche", "Fridrix Nitsshe", "1844–1900", "Faylasuf",
    "“Zardusht tavallosi”.",
    "philosophy", "ehtirosli, isyonkor"),
  f("sartre", "Jan-Pol Sartr", "1905–1980", "Faylasuf",
    "Ekzistensializm.",
    "philosophy", "shubhachi, jiddiy"),
  f("camus", "Alber Kamyu", "1913–1960", "Yozuvchi-faylasuf",
    "Absurd falsafasi.",
    "philosophy", "hayotsevar, mulohazali"),
  f("freud", "Zigmund Freyd", "1856–1939", "Psixoanalitik",
    "Psixoanaliz asoschisi.",
    "science", "kuzatuvchan, jiddiy"),
  f("jung", "Karl Yung", "1875–1961", "Psixolog",
    "Analitik psixologiya.",
    "science", "ramziy, chuqur"),

  // ====== Hukmdorlar / sarkardalar ======
  f("alexander", "Iskandar Zulqarnayn", "356–323 mil. av.", "Hukmdor",
    "Makedoniyalik Iskandar, ulkan saltanat asoschisi.",
    "ruler", "shijoatli, ulug‘vor"),
  f("caesar", "Yuliy Sezar", "100–44 mil. av.", "Rim diktatori",
    "Rim imperiyasiga zamin yaratgan.",
    "ruler", "qat’iy, notiq"),
  f("augustus", "Avgust", "63 mil. av.–14", "Birinchi Rim imperatori",
    "“Pax Romana” asoschisi.",
    "ruler", "siyosatchi, vazmin"),
  f("napoleon", "Napoleon Bonapart", "1769–1821", "Imperator",
    "Frantsuz imperator va sarkardasi.",
    "ruler", "ehtirosli, strategik"),
  f("genghis", "Chingizxon", "1162–1227", "Mo‘g‘ul xoqoni",
    "Tarixdagi eng katta saltanat asoschisi.",
    "ruler", "shafqatsiz qat’iy, jasur"),
  f("kublai", "Xubilayxon", "1215–1294", "Yuan imperatori",
    "Xitoyni birlashtirgan mo‘g‘ul xoqoni.",
    "ruler", "olijanob, siyosatchi"),
  f("suleiman", "Sulaymon Qonuniy", "1494–1566", "Usmonli sultoni",
    "Usmonli saltanatining oltin davri.",
    "ruler", "adolatli, viqorli"),
  f("mehmed-ii", "Fotih Sulton Mehmet", "1432–1481", "Sulton",
    "Konstantinopolni fath etgan.",
    "ruler", "yosh, jasur"),
  f("ashoka", "Ashoka", "304–232 mil. av.", "Hind imperatori",
    "Mauryalar sulolasining buyuk hukmdori.",
    "ruler", "tinchlikparvar, mehrli"),
  f("akbar", "Akbarshoh", "1542–1605", "Boburiy hukmdor",
    "Diniy bag‘rikenglik siyosati.",
    "ruler", "donishmand, bag‘rikeng"),
  f("aurangzeb", "Avrangzeb", "1618–1707", "Boburiy hukmdor",
    "Boburiylar saltanatining oxirgi qudratli hukmdori.",
    "ruler", "taqvodor, qat’iy"),
  f("shah-jahan", "Shoh Jahon", "1592–1666", "Boburiy hukmdor",
    "Toj Mahal quruvchisi.",
    "ruler", "nafis, romantik"),
  f("saladin", "Salohiddin Ayyubiy", "1137–1193", "Sulton",
    "Quddus fotihi.",
    "ruler", "olijanob, taqvodor"),
  f("harun", "Horun ar-Rashid", "766–809", "Abbosiy xalifa",
    "Bag‘dod oltin davri.",
    "ruler", "saxiy, ma’naviyatchi"),
  f("cleopatra", "Kleopatra", "69–30 mil. av.", "Misr malikasi",
    "Pomey va Sezar bilan ittifoq tuzgan.",
    "ruler", "ziyrak, jozibali"),
  f("elizabeth-i", "I Yelizaveta", "1533–1603", "Angliya qirolichasi",
    "“Oltin davr” malikasi.",
    "ruler", "siyosatchi, qat’iy"),
  f("victoria", "Qirolicha Viktoriya", "1819–1901", "Britaniya qirolichasi",
    "Viktoriya davri.",
    "ruler", "vazmin, an’anaviy"),
  f("catherine-ii", "II Yekaterina", "1729–1796", "Rus imperatorlari",
    "“Buyuk” imperator.",
    "ruler", "ma’rifatli, sho‘x"),
  f("peter-i", "I Pyotr", "1672–1725", "Rus imperatori",
    "Rossiyani islohotlar bilan o‘zgartirgan.",
    "ruler", "qat’iy, ishchan"),
  f("ivan-iv", "Ivan Grozniy", "1530–1584", "Rus podshohi",
    "Birinchi rus podshohi.",
    "ruler", "qattiqqo‘l, asabiy"),
  f("frederick-ii", "II Fridrix", "1712–1786", "Prussiya qiroli",
    "“Buyuk” qirol va sarkarda.",
    "ruler", "ma’rifatli, taktik"),
  f("hammurabi", "Xammurapi", "1810–1750 mil. av.", "Bobil podshohi",
    "Mashhur qonunlar to‘plami muallifi.",
    "ruler", "adolatli, qat’iy"),
  f("cyrus", "Buyuk Kir", "600–530 mil. av.", "Eron podshohi",
    "Ahmoniylar saltanati asoschisi.",
    "ruler", "olijanob, bag‘rikeng"),
  f("darius", "I Doro", "550–486 mil. av.", "Eron podshohi",
    "Buyuk Eron tashkilotchisi.",
    "ruler", "tartibli, qat’iy"),
  f("nebuchadnezzar", "II Navuxodonosor", "634–562 mil. av.", "Bobil podshohi",
    "Bobil osma bog‘lari quruvchisi.",
    "ruler", "shuhratparast, qudratli"),

  // ====== Yozuvchi / shoirlar ======
  f("shakespeare", "Uilyam Shekspir", "1564–1616", "Dramaturg",
    "Ingliz adabiyotining cho‘qqisi.",
    "writer", "she’riy, dramatik"),
  f("dante", "Dante Aligyeri", "1265–1321", "Shoir",
    "“Ilohiy komediya” muallifi.",
    "writer", "ramziy, tantanali"),
  f("homer", "Homer", "VIII asr mil. av.", "Shoir",
    "“Iliada” va “Odisseya” muallifi.",
    "writer", "epik, tantanali"),
  f("rumi", "Mavlono Jaloliddin Rumiy", "1207–1273", "Sufiy shoir",
    "“Masnaviy” muallifi.",
    "writer", "ishqiy, ma’naviy"),
  f("hafiz", "Hofiz Sheroziy", "1315–1390", "Shoir",
    "G‘azal ustasi.",
    "writer", "ishqiy, sirli"),
  f("ferdowsi", "Firdavsiy", "940–1020", "Shoir",
    "“Shohnoma” muallifi.",
    "writer", "epik, milliy"),
  f("omar-khayyam", "Umar Xayyom", "1048–1131", "Shoir, matematik",
    "Ruboiylar ustasi.",
    "writer", "falsafiy, hayotsevar"),
  f("saadi", "Saadi Sheroziy", "1210–1291", "Shoir",
    "“Guliston” va “Bo‘ston” muallifi.",
    "writer", "axloqiy, hikmatli"),
  f("nizami", "Nizomiy Ganjaviy", "1141–1209", "Shoir",
    "“Xamsa” muallifi.",
    "writer", "epik, ishqiy"),
  f("attar", "Farididdin Attor", "1145–1221", "Sufiy shoir",
    "“Mantiq ut-tayr” muallifi.",
    "writer", "ramziy, ma’naviy"),
  f("tolstoy", "Lev Tolstoy", "1828–1910", "Yozuvchi",
    "“Urush va tinchlik” muallifi.",
    "writer", "axloqiy, izlanuvchan"),
  f("dostoevsky", "Fyodor Dostoyevskiy", "1821–1881", "Yozuvchi",
    "“Jinoyat va jazo” muallifi.",
    "writer", "ruhshunos, ehtirosli"),
  f("pushkin", "Aleksandr Pushkin", "1799–1837", "Shoir",
    "Rus she’riyatining quyoshi.",
    "writer", "lirik, romantik"),
  f("chekhov", "Anton Chexov", "1860–1904", "Yozuvchi",
    "Hikoya va drama ustasi.",
    "writer", "lakonik, kuzatuvchan"),
  f("hemingway", "Ernest Xeminguey", "1899–1961", "Yozuvchi",
    "“Chol va dengiz” muallifi.",
    "writer", "qisqa, jasur"),
  f("kafka", "Frants Kafka", "1883–1924", "Yozuvchi",
    "“Jarayon” muallifi.",
    "writer", "absurd, tushli"),
  f("borges", "Xorxe Luis Borxes", "1899–1986", "Yozuvchi",
    "Adabiy labirintlar ustasi.",
    "writer", "ramziy, intellektual"),
  f("marquez", "Gabriel Garsia Markes", "1927–2014", "Yozuvchi",
    "“Yolg‘izlikning yuz yili” muallifi.",
    "writer", "sehrli realist, lirik"),
  f("hugo", "Viktor Hyugo", "1802–1885", "Yozuvchi",
    "“Achchiqlar” muallifi.",
    "writer", "romantik, jasur"),
  f("goethe", "Iogann Volfgang Gyote", "1749–1832", "Shoir",
    "“Faust” muallifi.",
    "writer", "polimat, lirik"),
  f("twain", "Mark Tven", "1835–1910", "Yozuvchi",
    "“Tom Soyer” muallifi.",
    "writer", "hazil, satirik"),
  f("orwell", "Jorj Oruell", "1903–1950", "Yozuvchi",
    "“1984” muallifi.",
    "writer", "sezgir, siyosatchi"),
  f("rowling", "J. K. Rouling", "1965–", "Yozuvchi",
    "“Garri Potter” muallifi.",
    "modern", "tasavvurli, axloqiy"),
  f("tolkien", "J. R. R. Tolkin", "1892–1973", "Yozuvchi",
    "“Uzuklar hukmdori” muallifi.",
    "writer", "afsonaviy, til ustasi"),
  f("austen", "Jeyn Ostin", "1775–1817", "Yozuvchi",
    "“G‘urur va xurofot” muallifi.",
    "writer", "ziyrak, kinoyali"),
  f("woolf", "Virjiniya Vulf", "1882–1941", "Yozuvchi",
    "Modern oqim ustasi.",
    "writer", "nozik, ruhshunos"),
  f("frost", "Robert Frost", "1874–1963", "Shoir",
    "Tabiat shoiri.",
    "writer", "sodda, chuqur"),
  f("whitman", "Uolt Uitmen", "1819–1892", "Shoir",
    "Amerika she’riyatining otasi.",
    "writer", "erkin, jo‘shqin"),

  // ====== San’atkorlar ======
  f("davinci", "Leonardo da Vinchi", "1452–1519", "Rassom, ixtirochi",
    "Uyg‘onish davri polimati.",
    "artist", "qiziquvchan, polimat"),
  f("michelangelo", "Mikelanjelo", "1475–1564", "Haykaltarosh, rassom",
    "Sikstina kapellasi muallifi.",
    "artist", "ehtirosli, mehnatkash"),
  f("raphael", "Rafael Santi", "1483–1520", "Rassom",
    "Uyg‘onish davrining nazokati.",
    "artist", "muloyim, uyg‘un"),
  f("vangogh", "Vinsent van Gog", "1853–1890", "Rassom",
    "Postimpressionizm ustasi.",
    "artist", "ehtirosli, tushkun"),
  f("monet", "Klod Mone", "1840–1926", "Rassom",
    "Impressionizm asoschisi.",
    "artist", "yorug‘lik izlovchi, nozik"),
  f("picasso", "Pablo Pikasso", "1881–1973", "Rassom",
    "Kubizm asoschisi.",
    "artist", "isyonkor, eksperimental"),
  f("dali", "Salvador Dali", "1904–1989", "Rassom",
    "Syurrealizm ustasi.",
    "artist", "g‘alati, dramatik"),
  f("rembrandt", "Rembrandt", "1606–1669", "Rassom",
    "Yorug‘-soya ustasi.",
    "artist", "ichki, mulohazali"),
  f("vermeer", "Yan Vermer", "1632–1675", "Rassom",
    "Niderland oltin davri.",
    "artist", "sokin, nozik"),
  f("frida", "Frida Kalo", "1907–1954", "Rassom",
    "Meksikaning ramzi.",
    "artist", "iztirobli, kuchli"),
  f("warhol", "Endi Uorxol", "1928–1987", "Rassom",
    "Pop-art asoschisi.",
    "artist", "kinoyali, zamonaviy"),
  f("bach", "Iogann Sebastyan Bax", "1685–1750", "Bastakor",
    "Klassik musiqaning otasi.",
    "artist", "tartibli, ilohiy"),
  f("mozart", "Volfgang Amadey Motsart", "1756–1791", "Bastakor",
    "Klassik davr dahosi.",
    "artist", "o‘ynoqi, salohiyatli"),
  f("beethoven", "Lyudvig van Betxoven", "1770–1827", "Bastakor",
    "9-simfoniya muallifi.",
    "artist", "ehtirosli, isyonkor"),
  f("chopin", "Frederik Shopen", "1810–1849", "Bastakor",
    "Fortepiano she’ri.",
    "artist", "lirik, nozik"),
  f("tchaikovsky", "Pyotr Chaykovskiy", "1840–1893", "Bastakor",
    "“Oqqush ko‘li” muallifi.",
    "artist", "lirik, dramatik"),
  f("yunusxoja", "Yunus Rajabiy", "1897–1976", "Bastakor",
    "O‘zbek maqom ustasi.",
    "artist", "milliy, vazmin"),
  f("mukarrama-turgunbayeva", "Mukarrama Turg‘unboyeva", "1913–1978", "Raqqosa",
    "O‘zbek milliy raqsi.",
    "artist", "ifodali, sehrli"),
  f("tamara-khanum", "Tamara Xonim", "1906–1991", "Raqqosa, qo‘shiqchi",
    "Sharqning yulduzi.",
    "artist", "jo‘shqin, jozibali"),
  f("batir-zakirov", "Botir Zokirov", "1936–1985", "Qo‘shiqchi",
    "O‘zbek estrada otasi.",
    "artist", "lirik, romantik"),

  // ====== Ixtirochi / texnologlar ======
  f("gutenberg", "Iogann Gutenberg", "1400–1468", "Ixtirochi",
    "Bosma stanok ixtirochisi.",
    "inventor", "amaliy, vazmin"),
  f("wright", "Aka-uka Raytlar", "1867–1948", "Ixtirochi",
    "Birinchi samolyot quruvchisi.",
    "inventor", "muhandis, jasur"),
  f("bell", "Aleksandr Bell", "1847–1922", "Ixtirochi",
    "Telefon ixtirochisi.",
    "inventor", "tahliliy, izlanuvchan"),
  f("ford", "Genri Ford", "1863–1947", "Sanoatchi",
    "Konveyer ishlab chiqarish asoschisi.",
    "inventor", "amaliy, ishchan"),
  f("jobs", "Stiv Jobs", "1955–2011", "Tadbirkor",
    "Apple asoschisi.",
    "modern", "perfektsionist, vizioner"),
  f("gates", "Bill Geyts", "1955–", "Tadbirkor",
    "Microsoft asoschisi.",
    "modern", "tahliliy, hayrlovchi"),
  f("musk", "Ilon Mask", "1971–", "Tadbirkor",
    "Tesla, SpaceX asoschisi.",
    "modern", "jasur, kelajakparvar"),
  f("zuckerberg", "Mark Tsukerberg", "1984–", "Tadbirkor",
    "Facebook/Meta asoschisi.",
    "modern", "yosh, tezkor"),
  f("page", "Larri Peyj", "1973–", "Tadbirkor",
    "Google asoschisi.",
    "modern", "muhandis, kam gap"),
  f("brin", "Sergey Brin", "1973–", "Tadbirkor",
    "Google asoschisi.",
    "modern", "qiziquvchan, tahliliy"),
  f("bezos", "Jeff Bezos", "1964–", "Tadbirkor",
    "Amazon asoschisi.",
    "modern", "uzoqni ko‘zlovchi, intizomli"),
  f("knuth", "Donald Knut", "1938–", "Olim",
    "“Kompyuter dasturlash san’ati” muallifi.",
    "science", "puxta, ilmiy"),
  f("dijkstra", "Edsger Deykstra", "1930–2002", "Olim",
    "Algoritmlar ustasi.",
    "science", "tanqidiy, aniq"),
  f("ada", "Ada Lavleys", "1815–1852", "Matematik",
    "Birinchi dasturchi.",
    "science", "tasavvurli, aniq"),
  f("hopper", "Greys Xopper", "1906–1992", "Olim",
    "COBOL tilining otasi.",
    "science", "amaliy, sho‘x"),
  f("lovelace-ii", "Tim Berners-Li", "1955–", "Ixtirochi",
    "World Wide Web ixtirochisi.",
    "modern", "ochiq, ilmiy"),
  f("ritchie", "Dennis Ritchi", "1941–2011", "Olim",
    "C tili va UNIX hammuallifi.",
    "science", "kamtar, chuqur"),
  f("torvalds", "Linus Torvalds", "1969–", "Dasturchi",
    "Linux yadrosi muallifi.",
    "modern", "ochiq, qat’iy"),
  f("shannon", "Klod Shennon", "1916–2001", "Muhandis",
    "Axborot nazariyasi otasi.",
    "science", "ijodkor, o‘ynoqi"),
  f("nash", "Jon Nash", "1928–2015", "Matematik",
    "Nash muvozanati muallifi.",
    "science", "intuitiv, mulohazali"),

  // ====== Sayyoh / kashfiyotchi ======
  f("marco-polo", "Marko Polo", "1254–1324", "Sayyoh",
    "“Sayohatlar kitobi” muallifi.",
    "explorer", "qiziquvchan, hikoyachi"),
  f("ibn-battuta", "Ibn Battuta", "1304–1369", "Sayyoh",
    "30 yil sayohat qilgan.",
    "explorer", "qiziquvchan, ilmiy"),
  f("zheng-he", "Chjen He", "1371–1433", "Admiral",
    "Xitoy okean ekspeditsiyalari yetakchisi.",
    "explorer", "qudratli, intizomli"),
  f("columbus", "Xristofor Kolumb", "1451–1506", "Sayyoh",
    "Yangi Dunyoga sayohati.",
    "explorer", "jasur, ehtirosli"),
  f("magellan", "Fernando Magellan", "1480–1521", "Sayyoh",
    "Birinchi dunyoaylanish.",
    "explorer", "qat’iy, sarguzashtchi"),
  f("cook", "Jeyms Kuk", "1728–1779", "Kapitan",
    "Tinch okeani kashfiyotchisi.",
    "explorer", "tartibli, jasur"),
  f("amundsen", "Ruall Amundsen", "1872–1928", "Sayyoh",
    "Janubiy qutbga birinchi yetib borgan.",
    "explorer", "sabotli, sovuq qonli"),
  f("armstrong", "Neyl Armstrong", "1930–2012", "Kosmonavt",
    "Oyga qadam qo‘ygan birinchi inson.",
    "explorer", "vazmin, jasur"),
  f("gagarin", "Yuriy Gagarin", "1934–1968", "Kosmonavt",
    "Kosmosga uchgan birinchi inson.",
    "explorer", "jasur, samimiy"),
  f("hillary", "Edmund Xillari", "1919–2008", "Alpinist",
    "Everest cho‘qqisi fotihi.",
    "explorer", "qat’iy, kamtar"),
  f("cousteau", "Jak-Iv Kusto", "1910–1997", "Okeanograf",
    "Suv osti olamining elchisi.",
    "explorer", "qiziquvchan, romantik"),
  f("livingstone", "Devid Livingston", "1813–1873", "Sayyoh",
    "Afrika tadqiqotchisi.",
    "explorer", "imonli, mardona"),

  // ====== Ma’naviyat / din arboblari ======
  f("avicenna-spiritual", "Imom G‘azzoliy", "1058–1111", "Faylasuf",
    "“Ihyou ulumiddin” muallifi.",
    "spiritual", "donishmand, vazmin"),
  f("ibn-arabi", "Ibn Arabiy", "1165–1240", "Sufiy",
    "“Vahdat ul-vujud” ta’limoti.",
    "spiritual", "ramziy, sirli"),
  f("rabia", "Robia al-Adaviya", "717–801", "Sufiy ayol",
    "Ilohiy ishq vakili.",
    "spiritual", "ishqiy, kamtar"),
  f("mansur-hallaj", "Mansur Halloj", "858–922", "Sufiy",
    "“Ana al-Haq” deyuvchi.",
    "spiritual", "jasur, isyonkor"),
  f("imam-shafii", "Imom Shofeiy", "767–820", "Faqih",
    "Shofeiy mazhabi asoschisi.",
    "spiritual", "aniq, dono"),
  f("imam-malik", "Imom Molik", "711–795", "Faqih",
    "Molikiy mazhabi asoschisi.",
    "spiritual", "vazmin, sabrli"),
  f("imam-abu-hanifa", "Imom Abu Hanifa", "699–767", "Faqih",
    "Hanafiy mazhabi asoschisi.",
    "spiritual", "mulohazali, mantiqiy"),
  f("imam-ahmad", "Imom Ahmad ibn Hanbal", "780–855", "Faqih",
    "Hanbaliy mazhabi asoschisi.",
    "spiritual", "qat’iy, sabotli"),
  f("ibn-taymiyya", "Ibn Taymiya", "1263–1328", "Faqih",
    "Salafiy fikrning vakili.",
    "spiritual", "qat’iy, kurashchan"),
  f("imam-maturidi", "Abu Mansur Moturidiy", "853–944", "Aqida olimi",
    "Moturidiya maktabi asoschisi.",
    "spiritual", "mantiqiy, vazmin"),

  // ====== Modern shaxslar — yetakchilar, faollar ======
  f("gandhi", "Mahatma Gandi", "1869–1948", "Yetakchi",
    "Hind mustaqillik harakati yetakchisi.",
    "modern", "tinch, qat’iyatli"),
  f("mandela", "Nelson Mandela", "1918–2013", "Yetakchi",
    "Apartheidga qarshi kurashchi.",
    "modern", "kechirimli, viqorli"),
  f("mlk", "Martin Lyuter King", "1929–1968", "Yetakchi",
    "“Mening orzuim bor” notig‘i.",
    "modern", "ilhomli, taqvodor"),
  f("lincoln", "Avraam Linkoln", "1809–1865", "Prezident",
    "AQSh prezidenti, qulchilikni bekor qilgan.",
    "ruler", "samimiy, kuyunchak"),
  f("washington", "Jorj Vashington", "1732–1799", "Prezident",
    "AQShning birinchi prezidenti.",
    "ruler", "viqorli, kamtar"),
  f("jefferson", "Tomas Jefferson", "1743–1826", "Prezident",
    "Mustaqillik deklaratsiyasi muallifi.",
    "ruler", "ma’rifatli, polimat"),
  f("kennedy", "Jon F. Kennedi", "1917–1963", "Prezident",
    "AQShning 35-prezidenti.",
    "ruler", "yosh, ilhomli"),
  f("churchill", "Uinston Cherchill", "1874–1965", "Bosh vazir",
    "Britaniyaning urush davri yetakchisi.",
    "ruler", "notiq, qat’iyatli"),
  f("roosevelt", "Franklin Ruzvelt", "1882–1945", "Prezident",
    "Yangi kurs siyosati.",
    "ruler", "vazmin, optimist"),
  f("teresa", "Ona Tereza", "1910–1997", "Xayriya arbobi",
    "Kambag‘allar himoyachisi.",
    "modern", "muloyim, fidoyi"),
  f("malala", "Malala Yusufzay", "1997–", "Faol",
    "Ta’lim huquqi himoyachisi.",
    "modern", "yosh, jasur"),
  f("anne", "Anna Frank", "1929–1945", "Yozuvchi qiz",
    "“Anna Frank kundaligi” muallifi.",
    "modern", "samimiy, umidvor"),
  f("helen", "Helen Keller", "1880–1968", "Faol",
    "Imkoniyati cheklanganlar uchun kurashchi.",
    "modern", "kuchli, ilhomli"),
  f("attaturk", "Mustafo Kamol Otaturk", "1881–1938", "Yetakchi",
    "Turkiya Respublikasi asoschisi.",
    "ruler", "qat’iy, islohotchi"),
  f("sun-yat-sen", "Sun Yatsen", "1866–1925", "Yetakchi",
    "Xitoy Respublikasi asoschisi.",
    "ruler", "vatanparvar, intizomli"),
  f("ho-chi-minh", "Xo Shi Min", "1890–1969", "Yetakchi",
    "Vyetnam mustaqilligi rahbari.",
    "ruler", "kamtar, qat’iy"),
  f("che", "Che Gevara", "1928–1967", "Inqilobchi",
    "Lotin Amerikasi inqilobi ramzi.",
    "modern", "isyonkor, romantik"),
  f("lenin", "Vladimir Lenin", "1870–1924", "Yetakchi",
    "SSSRga asos solgan.",
    "ruler", "tahliliy, qat’iy"),
  f("garibaldi", "Juzeppe Garibaldi", "1807–1882", "Sarkarda",
    "Italiya birlashuvi qahramoni.",
    "ruler", "jasur, romantik"),
  f("bolivar", "Simon Bolivar", "1783–1830", "Yetakchi",
    "Janubiy Amerika ozodlik harakati.",
    "ruler", "vatanparvar, qat’iy"),
  f("franklin", "Benjamin Franklin", "1706–1790", "Polimat",
    "AQSh asoschisi.",
    "modern", "amaliy, hazil"),
  f("alfred-nobel", "Alfred Nobel", "1833–1896", "Ixtirochi",
    "Dinamit ixtirochisi, Nobel mukofoti muassisi.",
    "inventor", "tinchlikparvar, izlanuvchan"),
  f("carnegie", "Endryu Karnegi", "1835–1919", "Sanoatchi",
    "Po‘lat magnati va xayriyachi.",
    "modern", "tadbirkor, saxiy"),
  f("rockefeller", "Jon Rokfeller", "1839–1937", "Sanoatchi",
    "Standard Oil asoschisi.",
    "modern", "intizomli, hisobchi"),
  f("ali", "Muhammad Ali", "1942–2016", "Sportchi",
    "“Eng buyuk” bokschi.",
    "modern", "jasur, jo‘shqin"),
  f("pele", "Pele", "1940–2022", "Futbolchi",
    "“Qirol Pele”.",
    "modern", "sho‘x, samimiy"),
  f("maradona", "Diego Maradona", "1960–2020", "Futbolchi",
    "Argentina afsonasi.",
    "modern", "ehtirosli, isyonkor"),
  f("jordan", "Maykl Jordan", "1963–", "Basketbolchi",
    "Eng buyuk basketbolchi.",
    "modern", "g‘olib, qat’iy"),
  f("messi", "Lionel Messi", "1987–", "Futbolchi",
    "Zamonaviy futbol dahosi.",
    "modern", "kamtar, nafis"),
  f("ronaldo", "Kristiano Ronaldu", "1985–", "Futbolchi",
    "Portugaliya yulduzi.",
    "modern", "mehnatkash, ishonchli"),
  f("schweitzer", "Albert Shvayser", "1875–1965", "Tabib, faylasuf",
    "Afrikadagi shifokor-missioner.",
    "modern", "fidoyi, falsafiy"),
  f("nightingale", "Florens Naytingeyl", "1820–1910", "Hamshira",
    "Zamonaviy hamshiralik asoschisi.",
    "modern", "rahmdil, intizomli"),
];

export function getFigure(id: string): Figure | undefined {
  return FIGURES.find((x) => x.id === id);
}

export const FEATURED = FIGURES.filter((x) => x.featured);