/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as FiguresIdRouteImport } from './routes/figures.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LessonsRoute,
} as any)
const FiguresIdRoute = FiguresIdRouteImport.update({
  id: '/figures/$id',
  path: '/figures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/api/chat': typeof ApiChatRoute
  '/figures/$id': typeof FiguresIdRoute
  '/lessons/$id': typeof LessonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/api/chat': typeof ApiChatRoute
  '/figures/$id': typeof FiguresIdRoute
  '/lessons/$id': typeof LessonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/api/chat': typeof ApiChatRoute
  '/figures/$id': typeof FiguresIdRoute
  '/lessons/$id': typeof LessonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lessons'
    | '/quiz'
    | '/api/chat'
    | '/figures/$id'
    | '/lessons/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lessons' | '/quiz' | '/api/chat' | '/figures/$id' | '/lessons/$id'
  id:
    | '__root__'
    | '/'
    | '/lessons'
    | '/quiz'
    | '/api/chat'
    | '/figures/$id'
    | '/lessons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  QuizRoute: typeof QuizRoute
  ApiChatRoute: typeof ApiChatRoute
  FiguresIdRoute: typeof FiguresIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/figures/$id': {
      id: '/figures/$id'
      path: '/figures/$id'
      fullPath: '/figures/$id'
      preLoaderRoute: typeof FiguresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LessonsRouteChildren {
  LessonsIdRoute: typeof LessonsIdRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsIdRoute: LessonsIdRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsRoute: LessonsRouteWithChildren,
  QuizRoute: QuizRoute,
  ApiChatRoute: ApiChatRoute,
  FiguresIdRoute: FiguresIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
